import { CafeConfig, MenuCategory, MenuItem } from '@/types/cafe';

export const defaultCafeConfig: CafeConfig = {
  id: 'artisanal-roast-01',
  slug: 'artisanal-roast',
  name: 'The Artisanal Roast & Co.',
  tagline: 'Craft Coffee, Sourdough Bakes & Calm Vibes',
  logoUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=150&q=80',
  heroImageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
  theme: {
    primaryColor: '#c27803', // Warm golden amber
    accentColor: '#362208',  // Deep roasted coffee
    fontFamily: 'Inter, sans-serif',
    borderRadius: '1rem',
    isDarkByDefault: false,
  },
  contact: {
    phone: '+91 98765 43210',
    whatsappNumber: '919876543210',
    address: '42, 100ft Road, Indiranagar, Bengaluru, Karnataka 560038',
    googleMapsUrl: 'https://maps.google.com',
    instagramUrl: 'https://instagram.com',
    wifiName: 'Artisanal_Roast_Guest',
    wifiPassword: 'coffeeandchill',
  },
  hours: {
    openingTime: '08:00 AM',
    closingTime: '11:00 PM',
    daysDescription: 'Open Daily (Mon - Sun)',
    isOpenOverride: null,
  },
  currencySymbol: '₹',
  currencyCode: 'INR',
  enabledModules: {
    whatsappOrdering: true,
    tableBookings: true,
    loyaltyCard: true,
    gallery: true,
    wifiDetails: true,
  },
};

export const defaultCategories: MenuCategory[] = [
  { id: 'cat-espresso', name: 'Specialty Coffee', icon: '☕', order: 1, description: 'Single origin arabica, freshly roasted & brewed to perfection' },
  { id: 'cat-toasts', name: 'Artisan Sourdough', icon: '🥑', order: 2, description: 'Handcrafted sourdough fermented for 36 hours' },
  { id: 'cat-bites', name: 'Small Bites & Bowls', icon: '🥗', order: 3, description: 'Fresh, vibrant and wholesome cafe plates' },
  { id: 'cat-desserts', name: 'Bakery & Sweets', icon: '🥐', order: 4, description: 'Baked daily with real European butter' },
  { id: 'cat-refreshers', name: 'Coolers & Teas', icon: '🍹', order: 5, description: 'Cascara, cold brew tonic, and organic matcha' },
];

export const defaultMenuItems: MenuItem[] = [
  {
    id: 'item-flat-white',
    categoryId: 'cat-espresso',
    name: 'Melbourne Flat White',
    description: 'Double ristretto shot with velvety micro-foam milk. Sweet, intense and balanced.',
    price: 240,
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80',
    dietary: 'veg',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 5,
    tags: ['Espresso', 'Signature'],
  },
  {
    id: 'item-iced-spanish-latte',
    categoryId: 'cat-espresso',
    name: 'Iced Spanish Latte',
    description: 'Rich espresso poured over chilled sweetened condensed milk and fresh dairy over crystal ice.',
    price: 270,
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    dietary: 'veg',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 5,
    tags: ['Cold', 'Sweet'],
  },
  {
    id: 'item-aeropress-single-origin',
    categoryId: 'cat-espresso',
    name: 'Kalledevarapura Estate Pour-Over',
    description: 'Light roast specialty pour over. Tasting notes of ripe red berries, jasmine, and citrus zest.',
    price: 290,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    dietary: 'vegan',
    isBestseller: false,
    isAvailable: true,
    preparationTimeMinutes: 7,
    tags: ['Black Coffee', 'Manual Brew'],
  },
  {
    id: 'item-avocado-tartine',
    categoryId: 'cat-toasts',
    name: 'Hass Avocado & Feta Toast',
    description: 'Crushed Hass avocado on toasted country sourdough, pickled red onions, Danish feta, chili flakes, roasted seeds.',
    price: 360,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    dietary: 'veg',
    isBestseller: true,
    isAvailable: true,
    spicyLevel: 1,
    preparationTimeMinutes: 10,
    tags: ['Chef Pick', 'Healthy'],
  },
  {
    id: 'item-truffle-scramble',
    categoryId: 'cat-toasts',
    name: 'Truffle Mushroom Scrambled Egg Toast',
    description: 'Creamy French scrambled eggs with butter-sauteed wild mushrooms and white truffle oil on sourdough.',
    price: 390,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    dietary: 'egg',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 12,
    tags: ['High Protein'],
  },
  {
    id: 'item-smoked-chicken-toast',
    categoryId: 'cat-toasts',
    name: 'Herb-Smoked Chicken & Pesto Toast',
    description: 'Sous-vide smoked chicken breast, house basil-walnut pesto, cherry tomatoes, and shaved parmesan.',
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
    dietary: 'non-veg',
    isBestseller: false,
    isAvailable: true,
    preparationTimeMinutes: 12,
    tags: ['Savory'],
  },
  {
    id: 'item-parmesan-truffle-fries',
    categoryId: 'cat-bites',
    name: 'Parmesan & Truffle Hand-Cut Fries',
    description: 'Crisp golden double-fried potato wedges tossed in aged parmesan, parsley, and garlic truffle aioli dip.',
    price: 290,
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    dietary: 'veg',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 8,
    tags: ['Crowd Favourite'],
  },
  {
    id: 'item-falafel-hummus-bowl',
    categoryId: 'cat-bites',
    name: 'Beetroot Hummus & Warm Falafel Bowl',
    description: 'Velvety pink beetroot hummus, crispy herb falafels, spiced chickpeas, pickled cucumbers, and zaatar pita chips.',
    price: 380,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    dietary: 'vegan',
    isBestseller: false,
    isAvailable: true,
    preparationTimeMinutes: 10,
    tags: ['Vegan', 'Superfood'],
  },
  {
    id: 'item-croissant-almond',
    categoryId: 'cat-desserts',
    name: 'Double-Baked Frangipane Almond Croissant',
    description: 'Flaky buttery croissant filled with roasted almond cream, topped with toasted sliced almonds and powdered sugar.',
    price: 260,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    dietary: 'veg',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 2,
    tags: ['Fresh Baked'],
  },
  {
    id: 'item-basque-cheesecake',
    categoryId: 'cat-desserts',
    name: 'San Sebastian Burnt Basque Cheesecake',
    description: 'Caramelized burnt crust with an ultra-creamy molten center. Served with seasonal berry compote.',
    price: 340,
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    dietary: 'egg',
    isBestseller: true,
    isAvailable: false, // Demonstates Sold Out state!
    preparationTimeMinutes: 2,
    tags: ['Trending'],
  },
  {
    id: 'item-yuzu-cold-brew-tonic',
    categoryId: 'cat-refreshers',
    name: 'Yuzu & Rosemary Cold Brew Tonic',
    description: '18-hour steeped cold brew layered over elderflower-yuzu tonic, fresh rosemary sprig and dehydrated orange slice.',
    price: 280,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    dietary: 'vegan',
    isBestseller: true,
    isAvailable: true,
    preparationTimeMinutes: 4,
    tags: ['Refreshing', 'Signature'],
  },
  {
    id: 'item-matcha-lemonade',
    categoryId: 'cat-refreshers',
    name: 'Iced Ceremonial Uji Matcha Lemonade',
    description: 'First harvest Japanese ceremonial matcha hand-whisked and layered over freshly squeezed sparkling lemonade.',
    price: 310,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    dietary: 'vegan',
    isBestseller: false,
    isAvailable: true,
    preparationTimeMinutes: 5,
    tags: ['Antioxidant'],
  },
];
